const tools=[['🧮','Age Calculator','age-calculator'],['🪪','Aadhaar Validator','aadhaar'],['📞','Phone Lookup','phone'],['🔐','Hash Generator','hash'],['🖼️','Image Forensics','image-forensics'],['📄','Document Metadata','metadata'],['📡','IP Lookup','ip'],['📊','CDR Analysis','cdr'],['🌐','IPDR Analysis','ipdr'],['📱','IMEI Verifier','imei'],['🔗','MAC Lookup','mac'],['🧾','PAN Tools','pan'],['🏦','IFSC Lookup','ifsc'],['🚗','Vehicle Tools','vehicle'],['🧠','Fingerprint Matcher','fingerprint'],['🕵️','Steganography','steganography'],['🔎','OCR','ocr'],['🔳','QR Code Tools','qrcode'],['🔑','Password Generator','password'],['✍️','Signature Checksum','signature'],['🅰️','Punjabi Transliteration','transliterate'],['🔤','Font Converter','font-converter'],['⚖️','File Comparison','compare'],['📁','General PDF & Image Tools','general'],['💳','GST Tools','gst'],['📌','CDR/IPDR utilities','general']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app=document.querySelector('#app');
function render(){app.innerHTML='<div class="shell"><header class="top"><div class="topbar"><div class="brand">one-for-all<span>.</span></div><div class="nav"><button id="homeBtn" class="active">Home</button><button id="lookupBtn">DB Lab</button></div></div></header><main><section class="hero"><div class="card"><div class="eyebrow">Reeldrop-inspired workflow</div><h1>paste. pick.<br>use. dip.</h1><p>A single learning-focused shell for the tools extracted from the supplied Punjab ZIP. Database access is isolated behind a server-side adapter.</p><div class="inputrow"><input id="quick" placeholder="search a tool…"><button class="primary" id="search">find tool</button></div></div><div class="card"><div class="eyebrow">Project status</div><h2>One for All</h2><p class="muted">Tool shell + configurable Both-db proxy.</p><div class="stats"><div class="stat"><b>26</b><span>tool entries</span></div><div class="stat"><b>57</b><span>source HTML screens</span></div><div class="stat"><b>1</b><span>server API adapter</span></div></div><div class="warning">API credentials stay server-side. Never put the Both-db secret in browser JavaScript.</div></div></section><section class="section"><h2>Toolbox</h2><div class="muted">Open a bundled tool when available, otherwise open its source deployment.</div><div id="tools" class="tools"></div></section><section id="viewer" class="panel"></section><section class="footer">Learning project. Uses Reeldrop as UI inspiration; it is a separate implementation.</section></main></div>';drawTools(tools);document.querySelector('#lookupBtn').onclick=showDb;document.querySelector('#search').onclick=()=>filterTools(document.querySelector('#quick').value);document.querySelector('#quick').oninput=e=>filterTools(e.target.value);}
function drawTools(list){document.querySelector('#tools').innerHTML=list.map(([i,n,p])=>'<button class="tool" data-path="'+p+'"><span class="icon">'+i+'</span><b>'+esc(n)+'</b><small>Open integrated tool</small></button>').join('');document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>openTool(b.dataset.path));}
function filterTools(q){q=q.toLowerCase();drawTools(tools.filter(x=>x[1].toLowerCase().includes(q)||x[2].includes(q)));}
function toolUrl(path){return './public/punjab/'+path+'/index.html';}
function openTool(path){const t=tools.find(x=>x[2]===path);document.querySelector('#viewer').innerHTML='<div class="card"><h2>'+esc(t?.[1]||path)+'</h2><p class="muted">If the bundled page is not present in your deployment, this opens the original static source.</p><div class="iframe-wrap"><iframe title="tool" src="'+toolUrl(path)+'"></iframe></div></div>';document.querySelector('#viewer').scrollIntoView({behavior:'smooth'});}
function showDb(){document.querySelector('#viewer').innerHTML='<div class="card"><div class="eyebrow">Both-db adapter</div><h2>API Lab</h2><p class="muted">The browser calls only <code>/api/lookup</code>. The upstream URL and secret belong in server environment variables.</p><div class="tabs"><button class="chip active" data-kind="number">Number</button><button class="chip" data-kind="aadhar">Aadhaar</button></div><div class="lookup"><input id="dbValue" placeholder="synthetic test value"><button class="primary" id="dbRun">run lookup</button></div><div id="dbResult" class="result">Waiting for a test lookup…</div></div>';document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');});document.querySelector('#dbRun').onclick=runLookup;document.querySelector('#dbValue').value='TEST-0001';document.querySelector('#viewer').scrollIntoView({behavior:'smooth'});}
async function runLookup(){const value=document.querySelector('#dbValue').value.trim();const kind=document.querySelector('.chip.active')?.dataset.kind||'number';const out=document.querySelector('#dbResult');if(!value){out.textContent='Enter a synthetic test value.';return}out.textContent='Loading…';try{const r=await fetch('/api/lookup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,value})});const data=await r.json();out.textContent=JSON.stringify(data,null,2);}catch(e){out.textContent=JSON.stringify({status:'mock',message:'API adapter is not deployed yet.',query:{kind,value}},null,2);}}
render();