plugins { id 'com.android.application' }

android {
    namespace 'com.chatpataprani.hao'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.chatpataprani.hao'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
        buildConfigField "String", "BACKEND_URL", '"https://one-for-all.vercel.app/api/lookup"'
    }
}
