plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def haoBackendUrl = System.getenv("HAO_BACKEND_URL") ?: ""

android {
    namespace 'com.chatpataprani.hao'
    compileSdk 35
    buildFeatures { buildConfig true }
    defaultConfig {
        applicationId 'com.chatpataprani.hao'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '3.1'
        buildConfigField 'String', 'BACKEND_URL', '"' + haoBackendUrl.replace('"', '\\\"') + '"'
    }
}
